spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #쿼리 로그 Mysql로 변경
  profiles:
    include: oauth
    active: real
  session:
    store-type: jdbc
---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
---
spring:profiles: real
spring.profiles.include: real-db






